PLUME_SCRIPTS ?= ../.plume-scripts
ifeq (,$(wildcard ${PLUME_SCRIPTS}))
dummy := $(shell git clone --depth=1 -q https://github.com/plume-lib/plume-scripts.git ${PLUME_SCRIPTS})
endif

.DELETE_ON_ERROR:
.PHONY: all default clean

all default: azure-pipelines.yml

%: %.m4 defs.m4 jobs.m4
	@chmod -f +w $@ || true
	m4 $< > $@
	${PLUME_SCRIPTS}/squeeze-blank-lines $@
	@chmod -w $@

clean:
	rm -f azure-pipelines.yml
